### ISSUE TITLE
Unable to run using go-web.bat

### ISSUE THREAD

**Issue by 3m377** [IAHispano/Applio-RVC-Fork#10]
When I run go-web.bat it returns with this error:
Traceback (most recent call last):
  File "D:\ai\RVC\installer-test\Applio-RVC-Fork\infer-web.py", line 13, in <module>
    import lib.globals.globals as rvc_globals
ModuleNotFoundError: No module named 'lib.globals'
I am running an Nvidia GTX 1660 Super with Python 3.7, 3.9, 3.10, and 3.11 installed.

**Comment by aitronssesin** [comment]
Yo only need python 3.9.8 to work if you have another version of python the progress at install the requirements will fail also did you execute? The install Applio.bat?

**Comment by blaise-tk** [comment]
For specific support on Applio, join our Discord server. In the help channel we will help you well.

https://discord.gg/iahispano
