### ISSUE TITLE
Support for older video cards

### ISSUE THREAD

**Issue by testermax90** [IAHispano/Applio-RVC-Fork#103]
Support for older video cards

Can you add support for Nvidia 700 and 900 series video cards, and similarly from amd, this may please people with such video cards.

**Comment by HyperChocolat** [comment]
It's impossible. Those cards do not support the API at the hardware level. Check this commit: https://github.com/IAHispano/Applio-RVC-Fork/commit/d635e9440687139a10b187ba27092cb2ee5b9143. Also, if you manage to bypass it somehow, your GPU will suffer.

**Comment by HyperChocolat** [comment]
And for AMD is even worse since they use a forked version of torch with weird changes. sometimes you may expect random bugs even if your AMD card is supported. also pip doesn't help with this situation (there are like 7 commits just trying to fix dependencies)
