### ISSUE TITLE
no .pth files is saved in logs/weight

### ISSUE THREAD

**Issue by Meawjin** [IAHispano/Applio-RVC-Fork#106]
no .pth files is saved in logs/weight , although  I already set save frequency = 10 and try to manual saved models

**Comment by HyperChocolat** [comment]
can you please bring logs about it?. if there isn't pths in logs/weights in the cmd should be a message saying smth about it. also check logs/modelname maybe is there

**Comment by Meawjin** [comment]
No message is shown something like "saved the model file"  between the line of epoch 10 to 11 in cmd,   and no pth file in logs/weights and logs/model_name     =====  this is cmd on epoch 9 to 11 ====>>> ( I already set save frequency =10)

INFO:JASMIN_V2:====> Epoch: 9 Step: 522 Learning Rate: 9.99e-05 [2023-10-28 23:14:28] | (0:07:26.024890)
INFO:JASMIN_V2:loss_gen_all=41.859, loss_disc=3.557, loss_gen=3.791, loss_fm=13.567, loss_mel=22.546, loss_kl=1.955
tensorboard is not running, cannot detect overtraining.
HTTPConnectionPool(host='localhost', port=7898): Max retries exceeded with url: /data/plugin/scalars/scalars?tag=loss%2Fg%2Ftotal&format=csv&run=. (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000019E283F5160>, 'Connection to localhost timed out. (connect timeout=1)'))


INFO:JASMIN_V2:====> Epoch: 10 Step: 580 Learning Rate: 9.9888e-05 [2023-10-28 23:21:14] | (0:06:42.923054)
INFO:JASMIN_V2:loss_gen_all=42.222, loss_disc=3.120, loss_gen=4.226, loss_fm=13.842, loss_mel=22.688, loss_kl=1.466
tensorboard is not running, cannot detect overtraining.
HTTPConnectionPool(host='localhost', port=7898): Max retries exceeded with url: /data/plugin/scalars/scalars?tag=loss%2Fg%2Ftotal&format=csv&run=. (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000019E278C9B50>, 'Connection to localhost timed out. (connect timeout=1)'))


INFO:JASMIN_V2:====> Epoch: 11 Step: 638 Learning Rate: 9.9875e-05 [2023-10-28 23:28:25] | (0:07:09.428005)
INFO:JASMIN_V2:loss_gen_all=44.240, loss_disc=3.370, loss_gen=4.139, loss_fm=15.665, loss_mel=23.003, loss_kl=1.433
tensorboard is not running, cannot detect overtraining.
HTTPConnectionPool(host='localhost', port=7898): Max retries exceeded with url: /data/plugin/scalars/scalars?tag=loss%2Fg%2Ftotal&format=csv&run=. (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000019E281AF2B0>, 'Connection to localhost timed out. (connect timeout=1)'))

**Comment by Meawjin** [comment]
is applio_installer 4.0.0 work correctly( above problem is from 4.0.1 ) ? ,   can I temporary use  4.0.0 old recent version?

**Comment by HyperChocolat** [comment]
> is applio_installer 4.0.0 work correctly( above problem is from 4.0.1 ) ? , can I temporary use 4.0.0 old recent version?

i mean if you already have 4.0.0 you can use it normally but if you want to install 4.0.0 is needed to clone the commits for 4.0.0

**Comment by HyperChocolat** [comment]
also nothing changed in training about the way the backups are being saved. this is so weird

**Comment by Meawjin** [comment]
thank u very much, I ll wait for it

**Comment by KawaiianPizza** [comment]
Try running `pip install tensorboard` and trying again

**Comment by Meawjin** [comment]
Thank u very much , I try to test it

ในวันที่ พ. 1 พ.ย. 2023 03:06 KawaiianPizza ***@***.***>
เขียนว่า:

**Comment by KawaiianPizza** [comment]
> Thank u very much , I try to test it

should be fixed if https://github.com/IAHispano/Applio-RVC-Fork/pull/110#issue-1971663392 goes through

**Comment by Meawjin** [comment]
Thank u...   I already tested it, it  s now work correctly
but I have 2 more questions.

1. if i want to use f0 setting ..How do I use f0 curve file in advance setting of Model inference( what folder and what file name do i have to drag into f0 curve box ?)
2. Can I pause training the model and train again next time to continue this training?, How to?

**Comment by KawaiianPizza** [comment]
> 1. if i want to use f0 setting ..How do I use f0 curve file in advance setting of Model inference( what folder and what file name do i have to drag into f0 curve box ?)

I don't know sorry
> 2. Can I pause training the model and train again next time to continue this training?, How to?

You should be able to by selecting the same settings that you first trained with but skipping process data and feature extraction
