### ISSUE TITLE
Trick google colab to get webui applio running

### ISSUE THREAD

**Issue by HyperChocolat** [IAHispano/Applio-RVC-Fork#109]
If you guys somehow nuke Linux Out-of-Memory Killer (maybe editing systemctl things since in colab we are the root user) on colab and use smart ways to clone it we could still using applio webui. also since we are using .venv for google colab things it will be harder to detect

**Comment by HyperChocolat** [comment]
@laynz28 ???

**Comment by laynz28** [comment]
ops sorry my bad
