### ISSUE TITLE
Stop training early if no improvement detected is broken

### ISSUE THREAD

**Issue by ccateni** [IAHispano/Applio-RVC-Fork#113]
Used an Hour + Dataset with RVMPE GPU and the software claims epoch 1 is the best using the Stop training early if no improvement detected (Set Training Epochs to something high like 9999) option with Improvement smoothness calculation at 0.975.

Here is the training log.
[train.log](https://github.com/IAHispano/Applio-RVC-Fork/files/13256901/train.log)

**Comment by KawaiianPizza** [comment]
What you could try is changing to smoothness to 0.99 to flatten out the curve at first. In your log the first epoch starts at 29.890 then goes up to 41.021 then slowly down into the 30's. It might have started trending downward even more if given enough time, I could look into changing to overtrain detection to be dynamic based on dataset length. Sorry for the long delay!
