### ISSUE TITLE
cannot unpack non-iterable NoneType object on edge tts generation

### ISSUE THREAD

**Issue by modpotato** [IAHispano/Applio-RVC-Fork#117]
literally just tried to use edge tts with a freshly trained model (it worked last night)
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/81768237/d1095ca0-1df6-4ade-88ed-97e5e0ecd44b)

**Comment by aitronssesin** [comment]
Your trained model has spaces in the name. That's probably why it's not working

**Comment by modpotato** [comment]
> Your trained model has spaces in the name. That's probably why it's not working

![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/81768237/80ba2f1e-f5f4-4ecb-aa9e-ac1e444b17b8)
i replaced all the spaces with an underscore and got the same result, any other possibilities?

**Comment by aitronssesin** [comment]
It's quite peculiar. Does it function with a different model?

**Comment by modpotato** [comment]
> It's quite peculiar. Does it function with a different model? And can you send all the log?

![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/81768237/fc2b113d-99bb-4dd8-a1e8-51f7eecaf0c2)
perfectly fine, no idea why

**Comment by aitronssesin** [comment]
I checked the code of the tts but it's al working properly and because you tried with another model and worked what options did you used to train the model that didn't work??
