### ISSUE TITLE
dependencies? required modules? 

### ISSUE THREAD

**Issue by DumeoSangollo** [IAHispano/Applio-RVC-Fork#121]
I followed the instruction and now I extracted runtime folder
every time I run go-applio.bat it says "No module named yada yada" things

so how can I install all the required library?
I guess all the modules are in the runtime folder but I don't know how to install them... maybe I could pip install all the modules separately? 

+ i executed go-applio-manager.bat and tried 'Update Applio + Dependencies' but it said there is no requirements.txt...

**Comment by aitronssesin** [comment]
What option you use to start Applio?
