### ISSUE TITLE
CUFFT_INTERNAL_ERROR

### ISSUE THREAD

**Issue by hpnyaggerman** [IAHispano/Applio-RVC-Fork#124]
### Environment
- **Operating System:**  Debian GNU/Linux 12 (bookworm) x86_64  6.1.0-9-amd64
- **Python Version:** 3.9.18
- **Conda Environment:** Yes
- **Hardware:** Dual NVIDIA RTX 4090 GPUs

### Issue Description
I am encountering a `RuntimeError: CUFFT_INTERNAL_ERROR` when attempting to extract features using Applio's voice generation module. This error appears to be linked to the `torch.stft` function call within the feature extraction process.

### Steps to Reproduce
1. Installed Applio using the provided Linux installer, which handled all dependency installations.
2. Selected a dataset and performed a preprocessing procedure.
3. Initiated feature extraction process.
4. Encountered the error during the execution of the feature extraction process.

### Error Log
The following is a snippet of the error trace for reference:

```
Traceback (most recent call last):
  File "/home/hkyouma/ai/voicegen/Applio-RVC-Fork/lib/infer/modules/train/extract/extract_f0_rmvpe.py", line 86, in go
    featur_pit = self.compute_f0(inp_path, f0_method)
  File "/home/hkyouma/ai/voicegen/Applio-RVC-Fork/lib/infer/modules/train/extract/extract_f0_rmvpe.py", line 52, in compute_f0
    f0 = self.model_rmvpe.infer_from_audio(x, thred=0.03)
  File "/home/hkyouma/ai/voicegen/Applio-RVC-Fork/lib/infer/infer_libs/rmvpe.py", line 616, in infer_from_audio
    mel = self.mel_extractor(
  File "/home/hkyouma/ai/voicegen/Applio-RVC-Fork/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hkyouma/ai/voicegen/Applio-RVC-Fork/lib/infer/infer_libs/rmvpe.py", line 530, in forward
    fft = torch.stft(
  File "/home/hkyouma/ai/voicegen/Applio-RVC-Fork/.venv/lib/python3.9/site-packages/torch/functional.py", line 641, in stft
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR
```

This error seems to occur for each file in the dataset during feature extraction.

### Additional Context
- No modifications were made to the Applio codebase.
- Despite the errors, the extraction process finishes "successfully".
- During the training, the same issue appears, and the training process terminates immediately.

I would appreciate any insights or suggestions on how to resolve this issue. Thank you for your assistance.

**Comment by hpnyaggerman** [comment]
It would appear the issue is caused by outdated torch version. Updating torch with pip to the upstream fixed the issue. I suggest bumping the dependency versions in requirements.txt.

**Comment by blaise-tk** [comment]
You have another issue opened.

**Comment by DanHues** [comment]
> It would appear the issue is caused by outdated torch version. Updating torch with pip to the upstream fixed the issue. I suggest bumping the dependency versions in requirements.txt.

Do you know what version of torch you updated to for this to work? Ive been looking around with no luck on it.
