### ISSUE TITLE
AMD GPU not working.

### ISSUE THREAD

**Issue by Astrocricket777** [IAHispano/Applio-RVC-Fork#129]
I have been looking for an AMD solution for RVC a ton lately and stumbled upon this, I read through and installed it, everything was working fine until I tried to train (step 3) I set the GPU index to 0, but it gave me the same text in cmd as all the others "GPU not detected - falling back to CPU".

Specs:

CPU - AMD Ryzen 5 5500
GPU - AMD RX 6650 XT
RAM - 32 GB
OS - Windows 10 Pro

**Comment by blaise-tk** [comment]
You can't train with AMD.

**Comment by Astrocricket777** [comment]
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/105763633/6595b883-ccb1-4c88-9d1a-90f03658c306)

**Comment by Aldair502** [comment]
> Is this referring to being used on linux or something? 🙁
> 
> ![image](https://private-user-images.githubusercontent.com/105763633/282972431-6595b883-ccb1-4c88-9d1a-90f03658c306.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NzkxMzgsIm5iZiI6MTcwMjg3ODgzOCwicGF0aCI6Ii8xMDU3NjM2MzMvMjgyOTcyNDMxLTY1OTViODgzLWNjYjEtNGM4OC05ZDFhLTkwZjAzNjU4YzMwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwNTUzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGFhY2M5NmRlMjI1M2RiZDAzMWE4MTBjZGZiOWQ4M2ZlZTM1MjI3ZDI4ZTk4ZGU3MzU2ZTUzMGQ3ZGRlYmY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LYMmMp32LhM1AnA3qM1E4bLUoVbQ_aMrn9YaPIqx9oY)

l think it kinda worked with ROCM on linux but it wasn't tested
