### ISSUE TITLE
Error while trying to run locally after using the local installer

### ISSUE THREAD

**Issue by CyberLykan** [IAHispano/Applio-RVC-Fork#13]
```
Current Settings:

Python command: "runtime\python.exe"
Port number: "7897"
Theme: "JohnSmith9982/small_and_pretty"

Set fp16_run to false in 32k.json
Set fp16_run to false in 40k.json
Set fp16_run to false in 48k.json
Set fp16_run to false in 32k.json
Set fp16_run to false in 40k.json
Set fp16_run to false in 48k.json
Using Language: en_US
Traceback (most recent call last):
  File "D:\Applio-RVC-Fork\infer-web.py", line 264, in <module>
    set_edge_voice = easy_infer.get_edge_voice()
  File "D:\Applio-RVC-Fork\easy_infer.py", line 1359, in get_edge_voice
    completed_process = subprocess.run(['edge-tts',"-l"], capture_output=True, text=True)
  File "subprocess.py", line 505, in run
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
Press any key to continue . . .
```

**Comment by aitronssesin** [comment]
Join our server to support you https://discord.gg/iahispano

**Comment by CyberLykan** [comment]
> Join our server to support you https://discord.gg/iahispano

Your server is not easy to use for English persons.

**Comment by RustyKit-JohnW** [comment]
I'm having the same issue
Found GPU NVIDIA GeForce GTX 1660 SUPER , force to fp32
Found GPU NVIDIA GeForce GTX 1660 SUPER , force to fp32
Using Language: en_US
Traceback (most recent call last):
  File "C:\Users\myhom\Applio-RVC-Fork\infer-web.py", line 264, in <module>
    set_edge_voice = easy_infer.get_edge_voice()
  File "C:\Users\myhom\Applio-RVC-Fork\easy_infer.py", line 1359, in get_edge_voice
    completed_process = subprocess.run(['edge-tts',"-l"], capture_output=True, text=True)
  File "subprocess.py", line 505, in run
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
Press any key to continue . . .

**Comment by TheUserNil** [comment]
> I'm having the same issue Found GPU NVIDIA GeForce GTX 1660 SUPER , force to fp32 Found GPU NVIDIA GeForce GTX 1660 SUPER , force to fp32 Using Language: en_US Traceback (most recent call last): File "C:\Users\myhom\Applio-RVC-Fork\infer-web.py", line 264, in set_edge_voice = easy_infer.get_edge_voice() File "C:\Users\myhom\Applio-RVC-Fork\easy_infer.py", line 1359, in get_edge_voice completed_process = subprocess.run(['edge-tts',"-l"], capture_output=True, text=True) File "subprocess.py", line 505, in run File "subprocess.py", line 951, in **init** File "subprocess.py", line 1420, in _execute_child FileNotFoundError: [WinError 2] The system cannot find the file specified Press any key to continue . . .

You install the dependencies correctly, because the error is that you don't have the edge-tts dependency installed.

Although you can do it manually
pip install edge-tts

**Comment by aitronssesin** [comment]
If you don't want u tell you how to fix it at the installer it tells you to add one route to your environment variables

**Comment by aitronssesin** [comment]
And no you don't have to install python so the pip install command won't work for you the edge-tts is already installed but it isn't in the environment variables so it doesn't detect it

**Comment by aitronssesin** [comment]
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/74368135/ae779678-0362-41e6-99a0-8ac534f8ccaf)

**Comment by RustyKit-JohnW** [comment]
I've fixed the other issue now the issue is the WebUI isn't in English its all in Chinese from what i can tell
does anybody know how to fix that?

**Comment by aitronssesin** [comment]
It is contingent upon the language setting of your computer,

**Comment by RustyKit-JohnW** [comment]
> It is contingent upon the language setting of your computer,

My computer is set to English

**Comment by RustyKit-JohnW** [comment]
> It is contingent upon the language setting of your computer,

![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/126478004/685e613c-86e1-4b5f-a0b3-3a191fb0909f)
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/126478004/df24f86c-ad23-4719-b17b-cd111c662b91)

**Comment by aitronssesin** [comment]
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/74368135/37c4ac29-eff5-419c-85a7-1db4041ef11b)
Do you have the correct applio version? Reinstall it or update it.

**Comment by aitronssesin** [comment]
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/74368135/afba8489-606b-46f1-b11b-ebb23434baf4)
Se ve que en codigo detecta el lenguaje pero bueno haz esto cambia la linea 25 a language = "en_US"
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/74368135/312bb6de-0e79-4d3d-beb4-69ffb3024838)

**Comment by aitronssesin** [comment]
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/74368135/afba8489-606b-46f1-b11b-ebb23434baf4)
Certainly, you can change line 25 to set the language to "en_US."![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/74368135/312bb6de-0e79-4d3d-beb4-69ffb3024838)

**Comment by RustyKit-JohnW** [comment]
I can see if that works give me a sec

**Comment by RustyKit-JohnW** [comment]
Yes, i see it says language = "en_US" in my i18n.py file as well

**Comment by RustyKit-JohnW** [comment]
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/126478004/5f963e19-8938-4502-9f73-21760f779374)

**Comment by aitronssesin** [comment]
No the line 25 is 
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/74368135/ce0ba0ff-a1a2-4880-9fa6-f12a1c966e4c)
No 
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/74368135/e2422bd3-1d33-475c-a3e8-4aaf77a432d1)

**Comment by RustyKit-JohnW** [comment]
I see that why is mine in another spot? is that the issue?

**Comment by aitronssesin** [comment]
The code automatically detects the default language of the computer. However, if you wish to override this setting, you would need to follow the instructions I provided.

**Comment by RustyKit-JohnW** [comment]
Yup. which im trying to do but i cannot seem to edit anything because it looks the exact same other than             language = "en_US" not being in line 25 Everything i see is set to en_US

**Comment by aitronssesin** [comment]
"On line 27, the code sets the default language to English if the default language on your computer does not exist.

**Comment by aitronssesin** [comment]
It's not the same at line 25

**Comment by RustyKit-JohnW** [comment]
I Know that

**Comment by RustyKit-JohnW** [comment]
So what can i do to fix it?

**Comment by aitronssesin** [comment]
Change the line 25 to         language = "en_US"

**Comment by RustyKit-JohnW** [comment]
Okay. Testing now

**Comment by RustyKit-JohnW** [comment]
and its Still in Chinese

**Comment by aitronssesin** [comment]
The code you changed directly alters the language settings so theres not option that it's still in chinese

**Comment by RustyKit-JohnW** [comment]
And it even says when starting Applio
![Screenshot 2023-09-06 121257](https://github.com/IAHispano/Applio-RVC-Fork/assets/126478004/1c2e8cca-17f3-45e4-b630-ab4508b3447d)

**Comment by aitronssesin** [comment]
Kindly inspect the "en_US" file located in the "i18n" folder.

**Comment by RustyKit-JohnW** [comment]
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/126478004/ac7e8e52-0e33-4787-99e4-e8f25727d3ac)

**Comment by aitronssesin** [comment]
So and the Applio code is in english

**Comment by RustyKit-JohnW** [comment]
Yeah

**Comment by aitronssesin** [comment]
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/74368135/7e552e8b-18ff-4280-8876-024d95e670b2)

**Comment by aitronssesin** [comment]
Try clearing your browser cache or try in an alternate web browser.

**Comment by RustyKit-JohnW** [comment]
Just tried in another browser (OperaGX) instead of my usual chrome and nope still in Chinese
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/126478004/358c93e8-7963-4bbe-8e04-cabc00b83f07)

**Comment by aitronssesin** [comment]
Please examine the "infer web" file to ascertain if there is any content in Chinese.

**Comment by RustyKit-JohnW** [comment]
gpu_info = "\n".join(gpu_infos) if if_gpu_ok and gpu_infos else i18n("很遗憾您这没有能用的显卡来支持您训练")

i18n.print()
# 判断是否有能用来训练和加速推理的N卡

                    with gr.Row(): # Defines output info + output audio download after conversion
                        vc_output1 = gr.Textbox(label=i18n("输出信息"))
                        vc_output2 = gr.Audio(label=i18n("输出音频(右下角三个点,点了可以下载)"))
                        
                        
                                        with gr.TabItem(i18n("批处理")): # Dont Change
                    with gr.Group(): # Markdown explanation of batch inference
                        gr.Markdown(
                            value=i18n("批量转换, 输入待转换音频文件夹, 或上传多个音频文件, 在指定文件夹(默认opt)下输出转换的音频. ")
                        )
                        with gr.Row():
                            with gr.Column():
                                vc_transform1 = gr.Number(
                                    label=i18n("变调(整数, 半音数量, 升八度12降八度-12)"), value=0
                                )
                                opt_input = gr.Textbox(label=i18n("指定输出文件夹"), value="opt")
                            with gr.Column():
                                file_index4 = gr.Dropdown(
                                    label=i18n("自动检测index路径,下拉式选择(dropdown)"),
                                    choices=get_indexes(),
                                    value=best_match_index_path1,
                                    interactive=True,
                                )
                                sid0.select(fn=match_index, inputs=[sid0], outputs=[file_index2, file_index4])

                                refresh_button.click(
                                    fn=lambda: change_choices()[1],
                                    inputs=[],
                                    outputs=file_index4,
                                )
                                index_rate2 = gr.Slider(
                                    minimum=0,
                                    maximum=1,
                                    label=i18n("检索特征占比"),
                                    value=0.75,
                                    interactive=True,
                                )
                            with gr.Row():
                                dir_input = gr.Textbox(
                                    label=i18n("输入待处理音频文件夹路径(去文件管理器地址栏拷就行了)"),
                                    value=os.path.join(now_dir, "audios"),
                                )
                                inputs = gr.File(
                                    file_count="multiple", label=i18n("也可批量输入音频文件, 二选一, 优先读文件夹")
                                )

                        with gr.Row():
                            with gr.Column():
                                # Create a checkbox for advanced batch settings
                                advanced_settings_batch_checkbox = gr.Checkbox(
                                    value=False,
                                    label=i18n("高级设置"),
                                    interactive=True,
                                )
                            
                                # Advanced batch settings container        
                                with gr.Row(visible=False) as advanced_settings_batch: # Initially hidden
                                    with gr.Row(label = i18n("高级设置[批量]"), open = False):
                                        with gr.Column():
                                            file_index3 = gr.Textbox(
                                                label=i18n("特征检索库文件路径,为空则使用下拉的选择结果"),
                                                value="",
                                                interactive=True,
                                            )

                                    f0method1 = gr.Radio(
                                        label=i18n(
                                            "选择音高提取算法,输入歌声可用pm提速,harvest低音好但巨慢无比,crepe效果好但吃GPU"
                                        ),
                                        choices=["pm", "harvest", "crepe", "rmvpe"],
                                        value="rmvpe",
                                        interactive=True,
                                    )
                                    filter_radius1 = gr.Slider(
                                        minimum=0,
                                        maximum=7,
                                        label=i18n(">=3则使用对harvest音高识别的结果使用中值滤波，数值为滤波半径，使用可以削弱哑音"),
                                        value=3,
                                        step=1,
                                        interactive=True,
                                    )
                                
                                    with gr.Row():
                                        format1 = gr.Radio(
                                            label=i18n("导出文件格式"),
                                            choices=["wav", "flac", "mp3", "m4a"],
                                            value="flac",
                                            interactive=True,
                                        )
                                        

                                    with gr.Column():
                                        resample_sr1 = gr.Slider(
                                            minimum=0,
                                            maximum=48000,
                                            label=i18n("后处理重采样至最终采样率，0为不进行重采样"),
                                            value=0,
                                            step=1,
                                            interactive=True,
                                        )
                                        rms_mix_rate1 = gr.Slider(
                                            minimum=0,
                                            maximum=1,
                                            label=i18n("输入源音量包络替换输出音量包络融合比例，越靠近1越使用输出包络"),
                                            value=1,
                                            interactive=True,
                                        )
                                        protect1 = gr.Slider(
                                            minimum=0,
                                            maximum=0.5,
                                            label=i18n(
                                                "保护清辅音和呼吸声，防止电音撕裂等artifact，拉满0.5不开启，调低加大保护力度但可能降低索引效果"
                                            ),
                                            value=0.33,
                                            step=0.01,
                                            interactive=True,
                                        )

**Comment by RustyKit-JohnW** [comment]
Quite a bit to say the least

**Comment by RustyKit-JohnW** [comment]
Theres alot more

**Comment by aitronssesin** [comment]
Your not using correct Applio in applio theres nothing in chinese

**Comment by aitronssesin** [comment]
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/74368135/55653aed-b03a-4d6f-b1df-c3dd27ff0949)

**Comment by RustyKit-JohnW** [comment]
Could you send me infer-web.py and east_infer.py? 
I installed Applio with the go-install-applio.bat from the github releases and it installed those files
if you could send me those files that may work

**Comment by RustyKit-JohnW** [comment]
Both those files have chinese after looking at them

**Comment by aitronssesin** [comment]
Utilize the release installer and run it from outside the application folder. Alternatively, you can execute the "Update Applio.bat" directly.

**Comment by RustyKit-JohnW** [comment]
Okay. ill try that

**Comment by RustyKit-JohnW** [comment]
I'm completely reinstalling it right now
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/126478004/63687b14-5343-43e3-abd7-c41b648ad7ce)

**Comment by aitronssesin** [comment]
Please verify whether the 'infer_web.py' file has undergone any modifications in the meantime.

**Comment by aitronssesin** [comment]
The runtime is being installed

**Comment by RustyKit-JohnW** [comment]
Yup infer_web got updated there's no Chinese in it anymore

**Comment by aitronssesin** [comment]
So I find the issue you downloaded the go-applio-installer thinking it was the installer but it is the installer to update the already installed applio

**Comment by aitronssesin** [comment]
And there was errors you didn't noticied because they are cleared after the repo is extracted

**Comment by RustyKit-JohnW** [comment]
So i just did some looking and the infer_web off of https://github.com/IAHispano/Applio-RVC-Fork seems to have Chinese in it for whatever reason what i find odd is why would that be getting installed?

**Comment by aitronssesin** [comment]
Not it does not have any we changed all to english

**Comment by aitronssesin** [comment]
The first message of the instaler

**Comment by aitronssesin** [comment]
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/74368135/e2fdd5c4-10d4-41a7-9962-fbc0f9b863a5)

**Comment by aitronssesin** [comment]
The route changes

**Comment by RustyKit-JohnW** [comment]
Already there 
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/126478004/2dd09445-8f22-41b1-b754-bc78acfca1d0)

**Comment by aitronssesin** [comment]
No xD in the path variable

**Comment by aitronssesin** [comment]
Do not create a new user variable

**Comment by aitronssesin** [comment]
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/74368135/360ad157-c82f-42e2-a74f-bfbc827f3235)

**Comment by RustyKit-JohnW** [comment]
Ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh LOL My bad i didn't even read that correctly i just assumed "path variable" was just add a user variable lol my bad

**Comment by aitronssesin** [comment]
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/74368135/e184ff9e-8ca8-41ce-85f0-5ad564ff26c4)

**Comment by RustyKit-JohnW** [comment]
i get it now

**Comment by RustyKit-JohnW** [comment]
It works now! 
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/126478004/18e3feed-bde7-4af5-9e49-fcc55574b355)
and its in english

**Comment by aitronssesin** [comment]
Enjoy using Applio!

**Comment by RustyKit-JohnW** [comment]
Thank You! Sorry for all the trouble lol

**Comment by aitronssesin** [comment]
No need to worry; we're here to help!
