### ISSUE TITLE
Crepe_Hop_Lenght stuck at 160

### ISSUE THREAD

**Issue by Rinka-Emina** [IAHispano/Applio-RVC-Fork#132]
Magio Crepe (Crepe_Hop_Lenght) stuck at 160, what ever i set it, low/high it keep infer at 160 only

![160](https://github.com/IAHispano/Applio-RVC-Fork/assets/13935167/09367b7f-65d2-4293-a33f-465e81c2f225)

**Comment by TheUserNil** [comment]
Update Applio https://github.com/IAHispano/Applio-RVC-Fork/commit/14fcf8774fa93def1ba362914a2ba551a2ca7f4f
