### ISSUE TITLE
Problem with Mode Collapse prevention feature

### ISSUE THREAD

**Issue by litsa-the-dancer** [IAHispano/Applio-RVC-Fork#134]
I've noticed that the new mode collapse prevention feature, which retrains the epoch if mode collapse occurs, has some issues. Specifically, when it retrains the epoch to prevent mode collapse, it resets the step count and the entire graph. This makes it challenging to track the number of steps the model has been trained and creates a messy graph. I suggest refining this feature to enhance the model's quality by avoiding mode collapses. Instead of resetting the step count and graph entirely, consider keeping them consistent for better readability. If possible, maintain the graph structure and steps without going back to zero. Thank you for considering my feedback, and feel free to contact me on Discord @litsa_the_dancer if you have more questions. Please keep me updated on any developments. (check Screenshots for reference) screenshot : https://media.discordapp.net/attachments/1175385770756931645/1175759067604598844/image.png?ex=656c65f6&is=6559f0f6&hm=1a686dd7a90780c8f64d8399c1e9474f7c1d0978b34e51895ffd6adbb1c29025&=&width=1440&height=497

**Comment by KawaiianPizza** [comment]
Hide the eval group to only see actual progress saved to the model instead of every run

**Comment by litsa-the-dancer** [comment]
> Hide the eval group to only see actual progress saved to the model instead of every run

https://cdn.discordapp.com/attachments/1124336134420439200/1182698273807552693/image.png?ex=6585a499&is=65732f99&hm=5b5ba266dd4da69811616a8435e34f373eebd4b8bd92c013e5dd8f168f86e335&
I did but the it just completely starts from zero without all the other lines showing up any more. Dont know if this is important but i am on paperspace
