### ISSUE TITLE
Training model gives "RuntimeError: GlooDeviceFactory::makeUVDevice(): interface or hostname can't be empty"

### ISSUE THREAD

**Issue by MarcoReckless** [IAHispano/Applio-RVC-Fork#137]
I don't really or know whether or not this is related to Applio or the original RVC, but I can't seem to fix it.

```
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to []:39507 (system error: 10049).

[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to []:39507 (system error: 10049).

Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "C:\RVC\RVC-beta0717\train_nsf_sim_cache_sid_load_pretrain.py", line 100, in run
    dist.init_process_group(
  File "C:\RVC\RVC-beta0717\runtime\lib\site-packages\torch\distributed\distributed_c10d.py", line 895, in init_process_group
    default_pg = _new_process_group_helper(
  File "C:\RVC\RVC-beta0717\runtime\lib\site-packages\torch\distributed\distributed_c10d.py", line 994, in _new_process_group_helper
    backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
	
RuntimeError: GlooDeviceFactory::makeUVDevice(): interface or hostname can't be empty

```
I'm getting this error when trying to create a new model, I already created a few models a long time ago so my guess is something that changed in my system.

**Comment by blaise-tk** [comment]
But are you using Applio? This seems RVC:
>   File "C:\RVC\RVC-beta0717\runtime\lib\site-packages\torch\distributed\distributed_c10d.py", line 895, in init_process_group

**Comment by MarcoReckless** [comment]
> But are you using Applio? This seems RVC:
> 
> > File "C:\RVC\RVC-beta0717\runtime\lib\site-packages\torch\distributed\distributed_c10d.py", line 895, in init_process_group

The log is from when I used RVC (I tried both the original RVC and Applio while trying to sort this out), but the error appears to be the exact same on Applio; it might be unrelated to Applio directly but as an RVC fork it gives me the same issue.

**Comment by Aldair502** [comment]
the error says it. change your windows hostname. this issue happend before

**Comment by MarcoReckless** [comment]
> the error says it. change your windows hostname. this issue happend before. since you are running it in actions may you can change it from cmd but idk i never tried it

For whatever reason my PC's hostname was blank, I thought it was set and that this was just a random error, now I can train properly.
I used the Rename-Computer option via PowerShell.
