### ISSUE TITLE
Errors with newest install bat file in Windows

### ISSUE THREAD

**Issue by JJune33** [IAHispano/Applio-RVC-Fork#138]
I got multiple errors with the batch installation. I will attach the screenshots. Can 
somebody help me with these please?

![Schermopname (6)](https://github.com/IAHispano/Applio-RVC-Fork/assets/86732453/8bf5abbd-c6ea-48a7-9242-f6f8c29808c2)
![Schermopname (3)](https://github.com/IAHispano/Applio-RVC-Fork/assets/86732453/9bf67d87-8743-4d74-b440-641ae2a0e172)
![Schermopname (4)](https://github.com/IAHispano/Applio-RVC-Fork/assets/86732453/1321c937-2d06-4320-8dd9-4e56d86dea35)

**Comment by aitronssesin** [comment]
https://docs.applio.org/faq/general/check_buildtools_installed/

**Comment by JJune33** [comment]
Thank you. I uninstalled the VisualStudio manual. After everything was deleted I reinstalled it and installed the two modules. That was the solution for my problem. Thank you very much.
