### ISSUE TITLE
Auto detect audio path doesn't detect the audio file

### ISSUE THREAD

**Issue by Bagashidayat1** [IAHispano/Applio-RVC-Fork#159]
i already put my audio file to assets/audios but it doesn't detect anything?

**Comment by Kaydax** [comment]
Have the same issue. Auto detect not working at all even though files exist. Uploading via webui and refreshing causes files to not appear in the auto detect yet exist in the folder

**Comment by Bagashidayat1** [comment]
> Have the same issue. Auto detect not working at all even though files exist. Uploading via webui and refreshing causes files to not appear in the auto detect yet exist in the folder

yeah thats it
