### ISSUE TITLE
go-tensorboard.bat suddenly 

### ISSUE THREAD

**Issue by ColbyDash** [IAHispano/Applio-RVC-Fork#161]
## Environment
- OS: Windows 11 Home
- Python Version: 3.9.13
- Hardware: NVIDIA GeForce RTX 3050

## Issue Description:
Prior to yesterday night, I was able to boot up Tensorboard normally without any issues. But now since then, go-tensorboard.bat repeatedly just closes a milisecond after the "Activating Conda environment..." message pops up on my screen. A similiar thing happens right after the reinstallation, conda environment download, and tensorboard fix options finishes in go-applio-manager.bat. The tensor-launch.py launches just fine though without the Conda environment. From a lot of tinkering these past couple of hours, I have deducted that something about the "%CONDA_ROOT_PREFIX%\condabin\conda.bat" activate "%INSTALL_ENV_DIR%" command is causing it through the conda.bat.

## Attempted solutions
- Doing a system restore made before an Windows update at around 11 am PST yesterday.
- Doing some small tweaks to the go-tensorboard.bat that doesn't really help whatsoever such as adding "call" before "activate" or replacing it with that in the "%CONDA_ROOT_PREFIX%\condabin\conda.bat" activate "%INSTALL_ENV_DIR%" command.
- Reinstalling a whole bunch of dependencies and programs, including Applio with both installers. The install_Applio-Windows.bat and Applio-Installer.4.0.1.exe. Both installers of which exit prematurely before completion. Both after extracting the runtime.zip downloaded with the .exe installer additionally presenting an exit code of 0 at the end of it and Tensorboard revealing itself to not have been installed
with an exit code of its own, 3 btw, when the .exe installer tries to boot Applio up.
- A lot of restarting, especially through Visual Studio from the .exe installer.
- Installing Anaconda over/with Miniconda.

**Comment by blaise-tk** [comment]
We are aware of the problem, we are investigating it, if you run the `python command .launch-launch.py` you will be able to open it.

**Comment by blaise-tk** [comment]
Solved.
