### ISSUE TITLE
ModuleNotFoundError - Tensorboard.

### ISSUE THREAD

**Issue by Berringer** [IAHispano/Applio-RVC-Fork#169]
## Environment
- OS: Windows 10
- Python Version: 3.10.6
- Hardware: Nvidia RTX 2060 SUPER

## Issue Description:
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/32061445/07c71271-5481-451c-8834-cb592373fa80)

## Attempted solutions
Tried to uninstall and reinstall tensorboard a few times.
There is a file in the script folder for tensorboard right now.
I tried to fix the env PATH to the Scripts folder but no go.

Earlier this year I messed up with the env variables real bad so I thought that could be the issue, but python works fine and other modules work fine. Only this one that will not stop bothering me.

**Comment by aitronssesin** [comment]
yep that's a current issue in the installation of applio

**Comment by aitronssesin** [comment]
Try downloading the latest version of the installer and install applio in the C: drive directory

**Comment by Berringer** [comment]
> yep that's a current issue in the installation of applio
> Try downloading the latest version of the installer and install applio in the C: drive directory

Ah I see. I just started to fiddle with Applio today, never used it before. And my C: drive is filled to the rim unfortunately.
But I will try that anyway, can remove some things. Ty for the tip!

**Comment by Berringer** [comment]
Nope, same issue. If it is known, is there not a fix for this?

**Comment by aitronssesin** [comment]
Check the documentation at https://docs.applio.org/faq/installation-method/conda/tensorboard-dependency/ for TensorBoard dependency installation via Conda.

Additionally, if Mingit fails during installation the dependencies don't install correctly, refer to https://docs.applio.org/faq/installation-method/conda/mingit-extraction-or-download-issues/. Install Git separately to address Mingit-related problems.

**Comment by Berringer** [comment]
> Check the documentation at https://docs.applio.org/faq/installation-method/conda/tensorboard-dependency/ for TensorBoard dependency installation via Conda.
> 
> Additionally, if Mingit fails during installation the dependencies don't install correctly, refer to https://docs.applio.org/faq/installation-method/conda/mingit-extraction-or-download-issues/. Install Git separately to address Mingit-related problems.

Thank you, will do! I think I've been reading through the first link quite well, but I will go through it again!
Not had any Mingit errors but I guess it could happen if/when I sort the Tensorboard one. 
Thank you again!

**Comment by coldasicee** [comment]
just want to leave a quick suggestion to the dev. It would be nice if you could leave the older installer versions on the release page because if an error like this happens we can download an old version that should be working correctly.

btw, I have the same error, tried changing drive units to my c:, like you suggested, and still got the error.

**Comment by aitronssesin** [comment]
The older version of installer version is broken. You can download a specific version from the commit history for that file. The issue should be fixed in the latest version. Please record the installer process to help identify the problem.

**Comment by aitronssesin** [comment]
Okay, I believe I've identified the issue. One of the dependencies was outdated and not compatible with the required version of Torch. I have fixed it.

**Comment by Berringer** [comment]
> Okay, I believe I've identified the issue. One of the dependencies was outdated and not compatible with the required version of Torch. I have fixed it. Try reinstalling.

Cool, I will try tomorrow, really need to sleep :) Thank you so much!

**Comment by coldasicee** [comment]
> Okay, I believe I've identified the issue. One of the dependencies was outdated and not compatible with the required version of Torch. I have fixed it. Try reinstalling.

thanks for the hard work! Merry Christmas btw, have a good rest!

**Comment by GH0STSecurity** [comment]
>not giving up! :)
i wish i could say that aswell, but yeah about 1 week of troubleshotting ALL MFING RVCs and ALL of them giving me errors and failing over and over again, not gonna ever look back at these bullshit again :'))

**Comment by GH0STSecurity** [comment]
>Not giving up! :)
>
i wish i could say that aswell, but yeah about 1 week of troubleshotting ALL MFING RVCs and ALL of them giving me errors and failing over and over again, not gonna ever look back at these bullshit again :'))
