### ISSUE TITLE
BUG: rmvpe_gpu not functioning (broken)

### ISSUE THREAD

**Issue by ingrid-z** [IAHispano/Applio-RVC-Fork#171]
## Environment
- OS: Windows 11 Pro 23H2 OS build 22631.2861
- Python Version: Doesn't use conda env now? is it still relevant? 3.9.18 I guess.
- Hardware: RTX 4080

## Issue Description:
- The feature extract with rmvpe_gpu has a bug with latest windows_installer.bat, when extract the feature the console shows a lot of /path/*.py instead of the processing files.
- It causes if you set hop length to 10, epoch up to 1000 then training you will get the filename_e10_s10 which it's suppose to be filename_e10_s920 or more steps .

## Attempted solutions
- Use rmvpe(cpu) works, but much slower.

Please fix it asap, thanks for your hard works.

**Comment by crichu894** [comment]
I confirm the issue mentioned. The option “rmvpe_gpu” cannot be used during model training. The problem started occurring after the commit
https://github.com/IAHispano/Applio-RVC-Fork/commit/32db1ae805a2169d25d348fdbdce4a38e0234550

**Comment by ingrid-z** [comment]
> I confirm the issue mentioned. The option “rmvpe_gpu” cannot be used during model training. The problem started occurring after the commit [32db1ae](https://github.com/IAHispano/Applio-RVC-Fork/commit/32db1ae805a2169d25d348fdbdce4a38e0234550)

I'd like update some info.
As I said rmvpe(cpu) works, but I did a test hop length 10 epoch 20, turns out the trained files totally unusable, because there is no sound coming from VC, I see it on the other device with db monitor actually has respond to my voice but volume just human being can't be hear.

**Comment by aitronssesin** [comment]
We are aware of the issue with rmvpe_gpu not functioning. This is likely due to our recent update to the latest version of Torch, which offers increased stability and greater compatibility for training with both new and older graphics cards. Thank you for bringing this to our attention; we are currently exploring potential solutions to address this issue.
