### ISSUE TITLE
After installation: No module named 'tensorboard'

### ISSUE THREAD

**Issue by delete-exe** [IAHispano/Applio-RVC-Fork#172]
## Environment
- OS: Windows 11, 64-bit
- Python Version: 3.9.8
- Hardware: i9, 128 GB RAM, GT1030, M2.NVe 2 TB

## Issue Description:
Installed Phyton 3.9.8 and then installed Applio via "C:\Applio RVC\install_Applio.bat". 
After that, I openend the go-applio-manager.bat and went from 1 to 6 through the list, with all tasks successfully completed.

When I start Applio via go-applio.bat, I get the message:

```
Starting Applio-RVC-Fork with Conda default compatible with all platforms...
Traceback (most recent call last):
  File "C:\Applio RVC\infer-web.py", line 3, in <module>
    from tensorboard import program
ModuleNotFoundError: No module named 'tensorboard'
```
After that it closes on any key.
What can I do?

**Comment by aitronssesin** [comment]
https://docs.applio.org/faq/installation-method/conda/tensorboard-dependency/
