### ISSUE TITLE
BUG: Error when launching

### ISSUE THREAD

**Issue by Kilgorio** [IAHispano/Applio-RVC-Fork#173]
## Environment
- OS: Windows 11 
- Python Version: 3.10.9
- Hardware: RX 6600

## Issue Description:
```
When I start it, it gives me an this error message:
Traceback (most recent call last):
  File "D:\RVC-GUI-pkg\Applio-RVC-Fork\infer-web.py", line 60, in <module>
    from lib.modules.vc.modules import VC
  File "D:\RVC-GUI-pkg\Applio-RVC-Fork\lib\modules\vc\modules.py", line 12, in <module>
    from lib.modules.infer.infer_pack.models import (
  File "D:\RVC-GUI-pkg\Applio-RVC-Fork\lib\modules\infer\infer_pack\models.py", line 12, in <module>
    from torch.nn.utils.parametrizations import spectral_norm, weight_norm
ImportError: cannot import name 'weight_norm' from 'torch.nn.utils.parametrizations' (D:\RVC-GUI-pkg\Applio-RVC-Fork\env\lib\site-packages\torch\nn\utils\parametrizations.py)
```

## Attempted solutions
Reinstalling and basically every option in the manager

**Comment by Kilgorio** [comment]
I have to add that I updated and this started happening

**Comment by ColbyDash** [comment]
I just updated as well and this has been popping up for me also. I thought it was _go-applio.bat_ at first with it no longer sporting any of the choice entry options but nada, it goes deeper than that..

**Comment by Kilgorio** [comment]
Reinstalling it for a third time worked somehow

**Comment by ColbyDash** [comment]
> Reinstalling it for a third time worked somehow

Glad to hear that it worked for you also! After three tries though Lol
