### ISSUE TITLE
Not all Files are included in the Download Process

### ISSUE THREAD

**Issue by Raccooncity1998** [IAHispano/Applio-RVC-Fork#174]
OS: Windows 11
    Python Version: 3.9
    Hardware: GeForce 1070

This is the worst installation process I've ever experienced. most similar AI apps come with a packed file where you can download, extract and run instantly.  at first I tried installing this app using the bat file and I ended up getting this message:

`Applio has been successfully downloaded, run the file go-applio.bat to run the web interface!`

Since I couldn't find go-applio.bat I tried running it again and I noticed in the console that some files (namely requirements.txt) were missing:

> -ERROR: Could not open requirements file: [Errno 2] No such file or directory: '\\Applio-RVC-Fork\\assets\\requirements\\requirements.txt'

Then I accidentally saw the "assets" folder on the main page (which was supposed to contain the .txt files). I downloaded and extracted 
it next to the two folders (env and lib) that the app had already downloaded.

I ran the bat file again and it started downloading some other extra files, so on and so forth up to the point that I got another error:

> No module named tensorboard

I was going to proceed further through go-applio-manager.bat which I completely gave up and removed everything.

**Comment by GH0STSecurity** [comment]
yeah man fuck this

**Comment by blaise-tk** [comment]
This is a problem caused by your computer because at some point it prevents the download of some files, make sure you have your antivirus disabled.

**Comment by aitronssesin** [comment]
Also the error could be from one of this reasons https://docs.applio.org/faq/installation-method/conda/tensorboard-dependency/
or this https://docs.applio.org/faq/installation-method/conda/mingit-extraction-or-download-issues/ or this https://docs.applio.org/faq/installation-method/conda/error-downloading-miniconda/ check each to resolve your issue

**Comment by petermg** [comment]
I had this same problem, until I tried it again after DISABLING Windows Defender on Windows 11. It should state in the instructions that disabling your antivirus is a REQUIREMENT rather than "strongly suggested".

**Comment by blaise-tk** [comment]
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/133521603/075f3393-1be7-4720-9018-62aff5f0ce27)
