### ISSUE TITLE
BUG: Inaccurate dataset extracting's when using rmvpe-gpu

### ISSUE THREAD

**Issue by ColbyDash** [IAHispano/Applio-RVC-Fork#175]
## Environment
- OS: Windows 11 Home 
- Python Version: 3.9.13
- Hardware: NVIDIA GeForce RTX 3050

## Issue Description:
- In a continuation from another issue thread, #173 in specific, I encountered the same error as the OP in that issue but managed to fix it quickly after backing up Applio, creating a new folder for it, and starting a new install in there with no administrator perms when using it (I don't usually do that when installing Applio but just saying for clarification's sake) and the latest version of the installer bat. However I have come to notice that when using rmvpe-gpu as a extraction method, the trained model goes along super abnormally fast (goes from epoch to epoch under a second to be precise) and comes out sounding either high pitched or almost deep pitched but nothing at all like the voice of my choice from the dataset.

For reference of what this sounds like, I have attached a generation of what my current model SHOULD inherently sound like and a generation of the old model while I was using rmvpe-gpu just so y'all have an idea of what it sounds like.

https://github.com/IAHispano/Applio-RVC-Fork/assets/102436625/190af39c-1bc1-4a8d-ad41-d3712f98f6d9

EDIT: I may or may not have forgotten to include a log if needed:
[['libmodulestrainextractextract_f0_.txt](https://github.com/IAHispano/Applio-RVC-Fork/files/13789653/libmodulestrainextractextract_f0_.txt)

## Attempted solutions
- Using normal rmvpe rather than the GPU variation works a lot better than the latter in the meantime.

**Comment by aitronssesin** [comment]
https://github.com/IAHispano/Applio-RVC-Fork/issues/171

**Comment by ColbyDash** [comment]
> #171
Oh, didn't see that one but thank you for letting me know of its existence. 😄
