### ISSUE TITLE
BUG: New .pth incompatible with old RVC

### ISSUE THREAD

**Issue by LightningDragon** [IAHispano/Applio-RVC-Fork#177]
It appears that when the project transitioned to the new version of PyTorch, some key names in the dictionaries were altered. This change has rendered me unable to use a .pth file generated with Applio in the original RVC webUI. I assume this issue goes both ways, but I haven't tested it.

Regardless, a simple workaround is to perform a find-and-replace on the keys after executing `torch.load()`.

Here's an example of the changes:

Original keys:
```
weight.flow.flows.6.enc.res_skip_layers.1.weight_g
weight.flow.flows.6.enc.res_skip_layers.1.weight_v
```

Became:
```
weight.flow.flows.6.enc.res_skip_layers.1.parametrizations.weight.original0
weight.flow.flows.6.enc.res_skip_layers.1.parametrizations.weight.original1
```

**Comment by blaise-tk** [comment]
So you don't think the issue should go to RVC since they are using an older version?

**Comment by LightningDragon** [comment]
It all depends on how you want to handle compatibility. 

Anything expecting the serialization in the other format won't work with anything created after this change e.g. w-okada/voice-changer, etc., so it might make sense to do something like add a tab in the "Extra" section for converting back and forth. That is assuming you don't want the default to be the original format.

It's all up to you, I just thought I would post about it incase someone was in my situation and didn't know what the issue was or how to fix it without training for another 6 hours.

**Comment by LightningDragon** [comment]
Oh, and here's the code I used to convert the .pth in case some one needs it.

```
import torch
from collections import OrderedDict
cgp_grey = torch.load('cgp_grey_e400_s17200.pth', map_location=torch.device('cpu'))


def replace_keys_in_dict(d, old_key_part, new_key_part):
    # Use OrderedDict if the original is an OrderedDict
    if isinstance(d, OrderedDict):
        updated_dict = OrderedDict()
    else:
        updated_dict = {}

    for key, value in d.items():
        # Replace the key part if found
        new_key = key.replace(old_key_part, new_key_part)

        # If the value is a dictionary, apply the function recursively
        if isinstance(value, dict):
            value = replace_keys_in_dict(value, old_key_part, new_key_part)

        updated_dict[new_key] = value

    return updated_dict

torch.save(replace_keys_in_dict(replace_keys_in_dict(cgp_grey, '.parametrizations.weight.original1', '.weight_v'), '.parametrizations.weight.original0', '.weight_g'), 'cgp_grey_e400_s17200_fixed.pth')
```

**Comment by blaise-tk** [comment]
Because to me the trained models without that go me in inference, and if they work me in "won't work with anything created after this change e.g. w-okada/voice-changer, etc.,"

**Comment by LightningDragon** [comment]
Sorry I'm not sure I follow your grammar.

I'm not sure what "Because to me the trained models without that go me in inference" means.

I'm not sure what you are trying to get a cross, but the important part to be quoted is the "Anything expecting the serialization in the other format won't work with anything created after this change"

anything expecting 'weight.flow.flows.6.enc.res_skip_layers.1.weight_g' isn't going to work with a .pth that is using 'weight.flow.flows.6.enc.res_skip_layers.1.parametrizations.weight.original0' instead.

If your plan is for the .pth files you generate not to work with any software expecting the old format, that is fine. I just wanted you to know, that this is an issue someone using the tool has run into, and that there is a workaround to save the file instead of not being able to use it.

**Comment by blaise-tk** [comment]
> Sorry I'm not sure I follow your grammar.
> 
> I'm not sure what "Because to me the trained models without that go me in inference" means.
> 
> I'm not sure what you are trying to get a cross, but the important part to be quoted is the "Anything expecting the serialization in the other format won't work with anything created after this change"
> 
> anything expecting 'weight.flow.flows.6.enc.res_skip_layers.1.weight_g' isn't going to work with a .pth that is using 'weight.flow.flows.6.enc.res_skip_layers.1.parametrizations.weight.original0' instead.
> 
> If your plan is for the .pth files you generate not to work with any software expecting the old format, that is fine. I just wanted you to know, that this is an issue someone using the tool has run into, and that there is a workaround to save the file instead of not being able to use it.

I edited the message

**Comment by LightningDragon** [comment]
It doesn't look like the edit you mentioned saved. The message is still the same on my end.
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/6297205/5a41d540-6ce3-43fc-a8eb-27a5f67e863c)


Either way, I've gone ahead and uploaded file and the fixed version to a zip on hugging face so you can look them over if you want [weights.zip](https://huggingface.co/datasets/LightningDragon/test/blob/main/weights.zip)

cgp_grey_e400_s17200.pth is the file created by Applio and will simply produce static when used in w-okada or any other software expecting the old format.

cgp_grey_e400_s17200_fixed.pth is the file with the script I posted earlier applied to it.

**Comment by blaise-tk** [comment]
We will add the converter, but the problem really lies with the other software for not updating. What I wanted to tell you is when you encounter this problem, as I have used models trained in RVC Mainline and have had no problem.
