### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorboard'

### ISSUE THREAD

**Issue by Piqe2** [IAHispano/Applio-RVC-Fork#180]
I have now the go-bat, but... Now the cmd say this:(
El sistema no puede encontrar la ruta especificada.
Starting Applio-RVC-Fork with Conda default compatible with all platforms...
Traceback (most recent call last):
  File "C:\Applio\Applio-RVC-Fork\infer-web.py", line 3, in <module>
    from tensorboard import program
ModuleNotFoundError: No module named 'tensorboard'

**Comment by harvard1932** [comment]
same issue

**Comment by aitronssesin** [comment]
Check this https://docs.applio.org/faq/installation-method/conda/tensorboard-dependency/ also this https://docs.applio.org/faq/installation-method/conda/error-downloading-miniconda/ and this https://docs.applio.org/faq/installation-method/conda/mingit-extraction-or-download-issues/

**Comment by RaisingAwesome** [comment]
Same issue.  Here is what I have found so far:
 
To troubleshoot,  I ran go-applio-manager.bat.  I did the reinstall and selected the non-GPU option since I do not have nVidea.

This allowed it to proceed, but then led to the cannot import name 'weight_norm' bug which I am now troubleshooting.
