### ISSUE TITLE
ImportError: cannot import name 'weight_norm' from 'torch.nn.utils.parametrizations'

### ISSUE THREAD

**Issue by 39sdev** [IAHispano/Applio-RVC-Fork#182]
## Environment
- OS: Arch Linux (zen)
- Python Version: 3.9.18
- Hardware: NVIDIA RTX 2080 Ti

Traceback (most recent call last):
  File "/home/---/voice-changer/appliotts/Applio-RVC-Fork/infer-web.py", line 60, in <module>
    from lib.modules.vc.modules import VC
  File "/home/---/voice-changer/appliotts/Applio-RVC-Fork/lib/modules/vc/modules.py", line 12, in <module>
    from lib.modules.infer.infer_pack.models import (
  File "/home/---/voice-changer/appliotts/Applio-RVC-Fork/lib/modules/infer/infer_pack/models.py", line 12, in <module>
    from torch.nn.utils.parametrizations import spectral_norm, weight_norm
ImportError: cannot import name 'weight_norm' from 'torch.nn.utils.parametrizations' (/home/---/voice-changer/appliotts/Applio-RVC-Fork/.venv/lib/python3.9/site-packages/torch/nn/utils/parametrizations.py)
Press Enter to continue...

**Comment by RaisingAwesome** [comment]
Same problem. Web searches indicate it has to do with needing PyTorch 2.1, but I don't know how to update the environment successfully to fix it.

**Comment by 39sdev** [comment]
> Same problem. Web searches indicate it has to do with needing PyTorch 2.1, but I don't know how to update the environment successfully to fix it.
> 
> When I used go-appio-manager.bat to reinstall dependencies, I noticed this log item: Successfully installed torch-2.0.0+cu117 torchaudio-2.0.1+cu117 torchvision-0.15.1+cu117
> 
> I then found go-appio-manager.bat it installing the old dependency. I changed the torch install line to this: pip install torch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu121
> 
> I reran go-appio-manager.bat and did the reinstall. It then launched and worked with go-applio.bat

You are a saint!
