### ISSUE TITLE
Step 5: Export lowest points on a graph of the model doesn't work

### ISSUE THREAD

**Issue by ccateni** [IAHispano/Applio-RVC-Fork#20]
After training, I tried step 5 and it didn't work.
It either never loaded or when it did load, would just display nothing as if it was never pressed. No error showing up either.

**Comment by blaise-tk** [comment]
Locally or Colab?

**Comment by ccateni** [comment]
Local

**Comment by molotovah** [comment]
Same for me with the latest version

**Comment by Mefuuu** [comment]
works for me but sometimes shows not as many as selected

**Comment by blaise-tk** [comment]
We removed this feature because its so buggy 🥹

**Comment by cheezebone** [comment]
Aw, I was using it. It was very useful when it worked. Hopefully you can fix the bugs.

**Comment by Maelstrom2014** [comment]
I made an analysis of log file to choose lowest values. Anybody can inject this code to interface? 
![kholdall_graph_loss](https://github.com/IAHispano/Applio-RVC-Fork/assets/10183119/f4afcc75-a7c0-46e6-8f85-22281ea8c814)
