### ISSUE TITLE
The Applio Script Keeps Disconnecting From The Colab

### ISSUE THREAD

**Issue by owenborillo82** [IAHispano/Applio-RVC-Fork#22]
While I'm training my new model, the Applio Colab Script keeps disconnecting from the runtime itself while training my model for half an hour.

I'm training my model in 200 epochs, but I can't go higher than 200 since it keeps disconnecting itself from the Colab's Runtime. Also the UI crashes when I leave the UI for a half a minute to check the process on the Colab Tab.

I can't describe what causes the error, but I keep receiving "Something When Wrong" Error on the UI. I'm checking the Colab Tab and the UI back and forth, then I leaved for a minute, It disconnects itself again. Please fix this issue.
I wasted my time because of the errors.

I can't provide some screenshots, because literally, it just keeps disconnecting itself on the Colab's Runtime. No error codes or anything. Just an unexplainable disconnection.

**Comment by blaise-tk** [comment]
For support go to our Discord server.
