### ISSUE TITLE
Same Error as Bug Report #13

### ISSUE THREAD

**Issue by AsrielDewitt** [IAHispano/Applio-RVC-Fork#25]
**Describe the bug**
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/48144566/ad0dacab-b779-4c51-9a1c-15fb377b5bff)

**To Reproduce**
1. using the command `./runtime/python.exe infer-web.py --pycmd python --port 3000`

**Expected behavior**
Supposed to run the web GUi

**Device (please complete the following information):**
 - OS: Windows 11
 - GTX1650
 - 

**Platform (please complete the following information):**
 - Applio Local

**Comment by AsrielDewitt** [comment]
Attempt to resolve the issue, I go through the python script and issue with importing Tabs,

try to pip install it, and well

`
Traceback (most recent call last):
  File "F:\AI Voice Changer Stuff\New Applio\Applio-RVC-Fork-Recode\infer-web.py", line 61, in <module>
    import tabs.resources as resources
ModuleNotFoundError: No module named 'tabs.resources'
Press any key to continue . . .



`

**Comment by blaise-tk** [comment]
You must use the normal installer, not the beta/recode version, that version is in testing. If you need more specific assistance join the support server https://discord.gg/IAHispano
