### ISSUE TITLE
Applio folder isn't created

### ISSUE THREAD

**Issue by RompeCraneos** [IAHispano/Applio-RVC-Fork#26]
![Captura de pantalla (184)](https://github.com/IAHispano/Applio-RVC-Fork/assets/25283322/68486c49-412e-47c9-9558-3ca54b1a3b32)
Folder isn't created by script, please help

**Comment by blaise-tk** [comment]
Make sure you have correct permissions. For more help join the Discord

**Comment by RompeCraneos** [comment]
isn't about permissions, i tried changing folder name in script and error dissapear, but folder isn't created in base directory, i need to find path with these folders cloned

**Comment by Dolyfin** [comment]
If you ran the install script in admin, chances are its in your system32 folder.
