### ISSUE TITLE
Please, just bundle the python runtime and use that.

### ISSUE THREAD

**Issue by AsrielDewitt** [IAHispano/Applio-RVC-Fork#27]
I have several version of python installs on my PC, and I use multiple of them for MYRIAD of reasons.

if you bundle the runtime and use that, you could avoid versioning issue or just weird python issue in general.

So... WHY DIDN'T YOU.

because I have manually modified your batch script to use python 3.8 (because I don't have 3.9 installed).

and manually install the dependancy, and in the end, this is the result

`
Starting Applio...

Traceback (most recent call last):
  File "infer-web.py", line 26, in <module>
    ffmpeg = lazyload("ffmpeg")
  File "F:\AI Voice Changer Stuff\Applio\Applio-RVC-Fork\LazyImport.py", line 9, in lazyload
    loader = LazyLoader(spec.loader)
AttributeError: 'NoneType' object has no attribute 'loader'
Press any key to continue . . .

`

**Comment by blaise-tk** [comment]
Don't worry, the next update will not have runtime

**Comment by AsrielDewitt** [comment]
And how can you make sure that there ISN'T any missing dependencies? Because SciPy, even after it been install, STILL DOESN'T SHOW UP
