### ISSUE TITLE
ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by TroyanosNoGracias** [IAHispano/Applio-RVC-Fork#29]
**Describe the bug**
Getting an error when first launching applio (the one in the title)

**To Reproduce**
Install Applio, click on go-applio.bat, option 1, error pops

**Expected behavior**
I expect for applio to launch proper after installing.

**Screenshots / Video**
https://media.discordapp.net/attachments/1096880162257256618/1152300860433502328/image.png

**Device (please complete the following information):**
 - OS: Windows 10

**Platform (please complete the following information):**
 - Applio Local

**Comment by blaise-tk** [comment]
This will be fixed in the new Applio update
