### ISSUE TITLE
inter-web.py not working

### ISSUE THREAD

**Issue by DealPotato** [IAHispano/Applio-RVC-Fork#37]
Traceback (most recent call last):
  File "E:\Applio-RVC-Fork\infer-web.py", line 11, in <module>
    import lib.globals.globals as rvc_globals
ModuleNotFoundError: No module named 'lib.globals'
Press any key to continue . . .

using Python 3.9.X

**Comment by blaise-tk** [comment]
If you need support join the Discord server

**Comment by DealPotato** [comment]
your discord is fucking spainish god damn it. And no one cared about my problem.
