### ISSUE TITLE
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0) when running go-applio

### ISSUE THREAD

**Issue by Maximo-Rulli** [IAHispano/Applio-RVC-Fork#39]
Hi, I am getting the following error when running the go-applio.bat on any of the available configurations:
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
I have followed the setup steps, and it all seems to be correctly installed.
Thank you.

**Comment by Maximo-Rulli** [comment]
I have re-downloaded de repo, nonetheless, the error persists. Shall I do anything more?

**Comment by TheUserNil** [comment]
I can't give you a solution because the go-applio.bat doesn't make use of any .json, so it's rare that it appears.
