### ISSUE TITLE
GPU not found

### ISSUE THREAD

**Issue by skaba04** [IAHispano/Applio-RVC-Fork#41]
I have new conda enviroment. GPU: Nvidia RTX 4080 and applio cant find the GPU.

**Comment by skaba04** [comment]
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/116293460/ddc77963-448c-4823-bb4f-6b4cb261a043)

**Comment by aitronssesin** [comment]
If you need support join the Discord server
