### ISSUE TITLE
Some issues and feature requests

### ISSUE THREAD

**Issue by SouljaVR** [IAHispano/Applio-RVC-Fork#43]
Hi,

Thank you for your work - I had a few bug reports/suggestions to make things better:

1. [BUG] When adding audio to inference via the drag and drop menu, it does not auto detect the path. So if I drag audio in and press convert, it gives an error. You have to then manually select the audio via the dropdown. This is just weird behaviour, one extra step for no reason. Original RVC and Mangio RVC do not have this behaviour.

2. [Suggestion] Please bring back the original dataset path system. I don't know why this would be changed to a dropdown box/'dataset' folder in Applio. This doesn't make things easier. I'm sure a lot of people store their datasets on seperate storage etc. Please do not change things that don't need to be changed, the previous dataset selection system was fine.

3. [Suggestion] GPU selection for inference, so people with mismatched multi-GPU can prioritise tasks better. With training you can select the GPU but not for inference. Perhaps being able to switch between CPU/GPU rendering within RVC would be nice too. It would be handy if I could use the more powerful GPU to train at its full potential, and then use the weaker secondary GPU to infer audio.

4. [Suggestion] Voice presets. Not very important but it would be cool if we could create presets that auto select a specific model and fill in all the settings for it. I find myself using very varied settings for models, this would speed up workflow a little bit. Not important but would be a nice QOL upgrade!

Thanks again!

**Comment by Shadonkun** [comment]
Uploaded Voice model and index file are not showing in panels of selecting voice model and index file
