### ISSUE TITLE
Branch is broken on paperspace

### ISSUE THREAD

**Issue by Mojobones** [IAHispano/Applio-RVC-Fork#46]
For example, after installing, any attempts to run will result in an error about retrieving the user due to this code:

https://github.com/IAHispano/Applio-RVC-Fork/blob/main/assets/configs/config.py#L26

Which does not work on paperspace, nor does the line below that attempts to point at the python path on a windows box:

https://github.com/IAHispano/Applio-RVC-Fork/blob/main/assets/configs/config.py#L31

**Comment by blaise-tk** [comment]
We don't use paperspace so if you want to fix it we are open to PR!

**Comment by Mojobones** [comment]
I was going by the mentioning of paperspace integration on the home page https://github.com/IAHispano/Applio-RVC-Fork#paperspace-integration

It might be worth removing that part if it's not something you're looking to actively maintain atm. I'll give it a shot on windows instead.

**Comment by blaise-tk** [comment]
I understand what you mean, but we can't really test it. If you want to make a PR fixing that I'll wait to delete it, otherwise I'll delete it.

**Comment by TheUserNil** [comment]
> I was going by the mentioning of paperspace integration on the home page https://github.com/IAHispano/Applio-RVC-Fork#paperspace-integration
> 
> It might be worth removing that part if it's not something you're looking to actively maintain atm. I'll give it a shot on windows instead.

I have modified the code a bit, could you try again? If the error persists, could you help me find a solution

**Comment by Mojobones** [comment]
> > I was going by the mentioning of paperspace integration on the home page https://github.com/IAHispano/Applio-RVC-Fork#paperspace-integration
> > It might be worth removing that part if it's not something you're looking to actively maintain atm. I'll give it a shot on windows instead.
> 
> I have modified the code a bit, could you try again? If the error persists, could you help me find a solution

Looks like that fixed running the UI & CLI modes itself ("make run-ui" and "make run-cli") there is an issue with the requirements.txt where it seems to require pyworld but that's not compatible with linux. I had to go into assets/requirements and use "cat requirements.txt | xargs -n 1 pip install'" to have it install all the requirements properly instead of failing at pyworld. 

The easy solution would be to replace the call in the makefile with that if you don't want to mess around with requirements.txt as i'm not familiar enough with the code to know what pyworld is used for.
