### ISSUE TITLE
tensorboard in colab isn't working (error code 403)

### ISSUE THREAD

**Issue by AqilaAdnandana** [IAHispano/Applio-RVC-Fork#49]
tried to look arround in tensorboard in colab version always shows this:

![Screenshot 2023-09-23 at 7 50 28 PM](https://github.com/IAHispano/Applio-RVC-Fork/assets/62750631/e07c1c97-39bf-4d24-95fa-b62dc2ed25e7)

**Comment by blaise-tk** [comment]
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/133521603/0b3a171d-72b3-432a-8639-83a82412dae7)

**Comment by AqilaAdnandana** [comment]
i don't understand about the word "no works"
