### ISSUE TITLE
Bark TTS model doesn't seem to be able to load.

### ISSUE THREAD

**Issue by Atoli** [IAHispano/Applio-RVC-Fork#50]
No matter which voice i chose, it seems it cannot load bark TTS model at all.

![Capture1](https://github.com/IAHispano/Applio-RVC-Fork/assets/43733214/84e47044-bcb8-4599-bb25-0624a62bbc19)

What could be the problem?

**Comment by aitronssesin** [comment]
For more help join the Discord server. Apart that you are using python 3.10 insted of 3.9.8 bark is so slow so please use edge tts.
