### ISSUE TITLE
doesn't train the index

### ISSUE THREAD

**Issue by cvqez** [IAHispano/Applio-RVC-Fork#52]
The index is not trained, a second passes and the output window is empty. also 1 model epoch is trained in a second, is this normal?

**Comment by Maville-07** [comment]
your dataset didn't load correctly, it could be because the audios are in a format other than .wav or .flac or you exported/dived them with a program that doesn't encode the audios in the same way

**Comment by cvqez** [comment]
> your dataset didn't load correctly, it could be because the audios are in a format other than .wav or .flac or you exported/dived them with a program that doesn't encode the audios in the same way

okay, I downloaded it to mp3.

**Comment by Maville-07** [comment]
yap, that's the problem, you can convert them to wav with audacity or fl studio, it should fix it

**Comment by cvqez** [comment]
?

**Comment by Maville-07** [comment]
Try placing the audio path instead of uploading it inside applio, and if your audio is converted from mp3 to wav don't modify the frequenc

**Comment by blaise-tk** [comment]
The problem persists in the LATEST version of Applio?

**Comment by Foxie20** [comment]
i have the same problem, and on the latest version 3.0.8
