### ISSUE TITLE
Enhancement request adding RMVPE_onnx and RMVPE+

### ISSUE THREAD

**Issue by ingrid-z** [IAHispano/Applio-RVC-Fork#61]
1. add RMVPE_onnx and RMVPE+
2. adjustable hop length, I don't know if this help pitch accuracy. If no please enlight me.

I don't know if it possible for dev team. :)
Thanks for your hard works.

**Comment by blaise-tk** [comment]
these options already exist

**Comment by blaise-tk** [comment]
RMVPE_onnx and RMVPE+ already exist

**Comment by ingrid-z** [comment]
Sorry, I mean in Train tab. I do see there are in Model Inference tab.

**Comment by blaise-tk** [comment]
> 1. RMVPE_onnx

RMVPE_onnx is already available in the training, with respect to RMVPE+, its difference is that the pitch is more customizable, which in a training does not make much sense to add. We will take your suggestion to see if in the future we can train models directly with the modified pitch!
