### ISSUE TITLE
Feature Request: Variable Logging Interval based on Dataset length

### ISSUE THREAD

**Issue by Hit2Skill** [IAHispano/Applio-RVC-Fork#63]
Only getting logs every 200 intervals require small datasets to finish multiple epochs before getting reasonable output.
Would it be possible to adopt something of the [Mangio Fork to log on each finished epoch](https://github.com/Mangio621/Mangio-RVC-Fork/commit/e2994fcf73a46736447c2e15db1c296661f466f2)?

**Comment by TheUserNil** [comment]
> Only getting logs every 200 intervals require small datasets to finish multiple epochs before getting reasonable output. Would it be possible to adopt something of the [Mangio Fork to log on each finished epoch](https://github.com/Mangio621/Mangio-RVC-Fork/commit/e2994fcf73a46736447c2e15db1c296661f466f2)?

https://github.com/IAHispano/Applio-RVC-Fork/commit/8789147f5b03bbdb0a48767b0e533fac7e8f7c83

**Comment by Hit2Skill** [comment]
Thank you :)

You made my day with this.
