### ISSUE TITLE
Go Apollo is broken

### ISSUE THREAD

**Issue by ccateni** [IAHispano/Applio-RVC-Fork#66]
The go-apollo.bat file is broken. It opens, shows the logo, then closes.
Had to use a go-apollo.bat from a previous version to get the app working.
Please fix this.

**Comment by aitronssesin** [comment]
Fixed because in some pc's in the (  ) needs to be with ^( ^)

**Comment by aitronssesin** [comment]
Update Applio with the manager and delete the go applio file first or in the console use this command and then update git reset --hard
