### ISSUE TITLE
Updated everything, but it still errors using Mango-Crepe

### ISSUE THREAD

**Issue by ccateni** [IAHispano/Applio-RVC-Fork#75]
Updated everything, but it still shows:
"  File "F:\downloads\Apollov2\Applio-RVC-Fork\Applio-RVC-Fork\lib\infer\modules\train\extract\extract_f0_print.py", line 253, in go
    featur_pit = self.compute_f0(inp_path, f0_method, crepe_hop_length)
  File "F:\downloads\Apollov2\Applio-RVC-Fork\Applio-RVC-Fork\lib\infer\modules\train\extract\extract_f0_print.py", line 208, in compute_f0
    f0 = self.mncrepe(f0_method, x, p_len, crepe_hop_length)
  File "F:\downloads\Apollov2\Applio-RVC-Fork\Applio-RVC-Fork\lib\infer\modules\train\extract\extract_f0_print.py", line 78, in mncrepe
    crepe_hop_length,
NameError: name 'crepe_hop_length' is not defined"

_Originally posted by @ccateni in https://github.com/IAHispano/Applio-RVC-Fork/issues/65#issuecomment-1742237288_

**Comment by TheUserNil** [comment]
Are you sure you have updated it?  
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/102625768/caf364e4-8705-42a3-9be2-fd055974b06f)

**Comment by ccateni** [comment]
> Are you sure you have updated it? ![image](https://user-images.githubusercontent.com/102625768/271859186-caf364e4-8705-42a3-9be2-fd055974b06f.png)

I used the updater inside Apollo Manager including dependies.

**Comment by TheUserNil** [comment]
> > Are you sure you have updated it? ![image](https://user-images.githubusercontent.com/102625768/271859186-caf364e4-8705-42a3-9be2-fd055974b06f.png)
> 
> I used the updater inside Apollo Manager including dependies.

Possibly you have not been updated, so you can try these commands in the applio directory ( cmd )

`git init`
`git remote add origin https://github.com/IAHispano/Applio-RVC-Fork.git`
`git pull`

**Comment by ccateni** [comment]
After I did that update, looks like things are working again.
I had to download the Nvidia runtime, but it works so far.
Thanks
