### ISSUE TITLE
ModuleNotFoundError: No module named 'chardet'

### ISSUE THREAD

**Issue by loohney** [IAHispano/Applio-RVC-Fork#86]
This happens when downloading/cloning by myself as well as with the Applio Installer.

> is_half:True, device:cuda:0
> Traceback (most recent call last):
>   File "C:\Users\UserX\AppData\Roaming\Python\Python39\site-packages\aiohttp\client_reqrep.py", line 70, in <module>
>     import cchardet as chardet
> ModuleNotFoundError: No module named 'cchardet'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\UserX\Desktop\Applio-RVC-Fork\Applio-RVC-Fork\infer-web.py", line 63, in <module>
>     import tabs.tts as tts
>   File "C:\Users\UserX\Desktop\Applio-RVC-Fork\Applio-RVC-Fork\tabs\tts.py", line 22, in <module>
>     import edge_tts
>   File "C:\Users\UserX\Desktop\Applio-RVC-Fork\Applio-RVC-Fork\runtime\lib\site-packages\edge_tts\__init__.py", line 6, in <module>
>     from .communicate import Communicate
>   File "C:\Users\UserX\Desktop\Applio-RVC-Fork\Applio-RVC-Fork\runtime\lib\site-packages\edge_tts\communicate.py", line 26, in <module>
>     import aiohttp
>   File "C:\Users\UserX\AppData\Roaming\Python\Python39\site-packages\aiohttp\__init__.py", line 6, in <module>
>     from .client import (
>   File "C:\Users\UserX\AppData\Roaming\Python\Python39\site-packages\aiohttp\client.py", line 58, in <module>
>     from .client_reqrep import (
>   File "C:\Users\UserX\AppData\Roaming\Python\Python39\site-packages\aiohttp\client_reqrep.py", line 72, in <module>
>     import chardet  # type: ignore
> ModuleNotFoundError: No module named 'chardet'

**Comment by bygimenez** [comment]
https://docs.applio.org/faq/no-module/

**Comment by bygimenez** [comment]
> This happens when downloading/cloning by myself as well as with the Applio Installer.
> 
> > is_half:True, device:cuda:0
> > Traceback (most recent call last):
> > File "C:\Users\UserX\AppData\Roaming\Python\Python39\site-packages\aiohttp\client_reqrep.py", line 70, in 
> > import cchardet as chardet
> > ModuleNotFoundError: No module named 'cchardet'
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "C:\Users\UserX\Desktop\Applio-RVC-Fork\Applio-RVC-Fork\infer-web.py", line 63, in 
> > import tabs.tts as tts
> > File "C:\Users\UserX\Desktop\Applio-RVC-Fork\Applio-RVC-Fork\tabs\tts.py", line 22, in 
> > import edge_tts
> > File "C:\Users\UserX\Desktop\Applio-RVC-Fork\Applio-RVC-Fork\runtime\lib\site-packages\edge_tts__init__.py", line 6, in 
> > from .communicate import Communicate
> > File "C:\Users\UserX\Desktop\Applio-RVC-Fork\Applio-RVC-Fork\runtime\lib\site-packages\edge_tts\communicate.py", line 26, in 
> > import aiohttp
> > File "C:\Users\UserX\AppData\Roaming\Python\Python39\site-packages\aiohttp__init__.py", line 6, in 
> > from .client import (
> > File "C:\Users\UserX\AppData\Roaming\Python\Python39\site-packages\aiohttp\client.py", line 58, in 
> > from .client_reqrep import (
> > File "C:\Users\UserX\AppData\Roaming\Python\Python39\site-packages\aiohttp\client_reqrep.py", line 72, in 
> > import chardet  # type: ignore
> > ModuleNotFoundError: No module named 'chardet'

https://docs.applio.org/faq/no-module/

**Comment by loohney** [comment]
> https://docs.applio.org/faq/no-module/

Unfortunately this isn't working. Uninstalling/Installing 'chardet' works, however due to buildtools imcompatibility 'cchardet' isn't installing.
