### ISSUE TITLE
Bark TTS does not work. 

### ISSUE THREAD

**Issue by Yume02** [IAHispano/Applio-RVC-Fork#90]
I always get this "error": 

![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/123180992/e5ed1003-352a-4ed4-ac8f-bac05183ec7c)

Thank you for your help.

**Comment by HyperChocolat** [comment]
I think there is a place to put the api key but i don't remember. basically it's asking you to put the key or you may observe unexpected behaviors like the logs said

**Comment by wertos97** [comment]
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/18363190/9bf2f20d-b747-41f1-994a-9dc1da39bbe1)

can anyone confirm this?

**Comment by aitronssesin** [comment]
I confirm bark is so slow and is barely working now so use edge tts

**Comment by Yume02** [comment]
except that it doesn't solve the problem of bark which is much better than edge tts and so what's the answer rather than just closing my topic?

**Comment by aitronssesin** [comment]
No, Bark TTS is quite slow and not better, as Edge TTS offers greater clarity and operates much faster. In fact, Bark TTS is the opposite in terms of performance.
