### ISSUE TITLE
Whether the model has pitch guidance option ERROR.

### ISSUE THREAD

**Issue by Dolyfin** [IAHispano/Applio-RVC-Fork#96]
When trying to train a model without 'Whether the model has pitch guidance.' checked. Trying to train will output an error. I have not been able to identify why this error occurs. I have ensured the dataset is processed without issue.

```
Process Process-1:
Traceback (most recent call last):
  File "C:\Applio\Applio-RVC-Fork\lib\infer\modules\train\train.py", line 269, in run
    utils.latest_checkpoint_path(hps.model_dir, "D_*.pth"), net_d, optim_d
  File "C:\Applio\Applio-RVC-Fork\lib\infer\infer_libs\train\utils.py", line 212, in latest_checkpoint_path
    x = f_list[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "C:\Applio\Applio-RVC-Fork\lib\infer\modules\train\train.py", line 289, in run
    net_g.module.load_state_dict(
  File "C:\Applio\Applio-RVC-Fork\runtime\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs768NSFsid_nono:
        Unexpected key(s) in state_dict: "enc_p.emb_pitch.weight", "dec.m_source.l_linear.weight", "dec.m_source.l_linear.bias", "dec.noise_convs.0.weight", "dec.noise_convs.0.bias", "dec.noise_convs.1.weight", "dec.noise_convs.1.bias", "dec.noise_convs.2.weight", "dec.noise_convs.2.bias", "dec.noise_convs.3.weight", "dec.noise_convs.3.bias".
```

**Comment by HyperChocolat** [comment]
> When trying to train a model without 'Whether the model has pitch guidance.' checked. Trying to train will output an error. I have not been able to identify why this error occurs. I have ensured the dataset is processed without issue.
> 
> ```
> Process Process-1:
> Traceback (most recent call last):
>   File "C:\Applio\Applio-RVC-Fork\lib\infer\modules\train\train.py", line 269, in run
>     utils.latest_checkpoint_path(hps.model_dir, "D_*.pth"), net_d, optim_d
>   File "C:\Applio\Applio-RVC-Fork\lib\infer\infer_libs\train\utils.py", line 212, in latest_checkpoint_path
>     x = f_list[-1]
> IndexError: list index out of range
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "multiprocessing\process.py", line 315, in _bootstrap
>   File "multiprocessing\process.py", line 108, in run
>   File "C:\Applio\Applio-RVC-Fork\lib\infer\modules\train\train.py", line 289, in run
>     net_g.module.load_state_dict(
>   File "C:\Applio\Applio-RVC-Fork\runtime\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs768NSFsid_nono:
>         Unexpected key(s) in state_dict: "enc_p.emb_pitch.weight", "dec.m_source.l_linear.weight", "dec.m_source.l_linear.bias", "dec.noise_convs.0.weight", "dec.noise_convs.0.bias", "dec.noise_convs.1.weight", "dec.noise_convs.1.bias", "dec.noise_convs.2.weight", "dec.noise_convs.2.bias", "dec.noise_convs.3.weight", "dec.noise_convs.3.bias".
> ```

The issue persist?

**Comment by Qualzz** [comment]
Issue should not be closed It's still there.
