### ISSUE TITLE
Invoke-WebRequest : Forbidden when installing runtime

### ISSUE THREAD

**Issue by embis2003** [IAHispano/Applio-RVC-Fork#98]
<img width="879" alt="image" src="https://github.com/IAHispano/Applio-RVC-Fork/assets/59685827/690e7764-01ce-434f-8626-bb8a5ee3d089">

**Comment by CyberLykan** [comment]
I am also experiencing this issue.

**Comment by HyperChocolat** [comment]
download http://frippery.org/files/busybox/busybox.exe and put it in the folder. this is weird cuz i think the server wasn't even down this week or smth similar also you can change it to download runtime.zip insted of busybox.exe if you want to. may i change this to select a downloader

**Comment by HyperChocolat** [comment]
also please don't make two issues for the same thing [Cof cof](https://github.com/IAHispano/Applio-RVC-Fork/issues/102 ) it isn't even reporting smth it just says "im going to switch to mangio if you don't fix this immediately" remember that every pc is different and everyone doesn't have the same configs has you. thanks

**Comment by embis2003** [comment]
> also please don't make two issues for the same thing [Cof cof](https://github.com/IAHispano/Applio-RVC-Fork/issues/102) it isn't even reporting smth it just says "im going to switch to mangio if you don't fix this immediately" remember that every pc is different and everyone doesn't have the same configs has you. thanks

my bad yo

**Comment by HyperChocolat** [comment]
> > also please don't make two issues for the same thing [Cof cof](https://github.com/IAHispano/Applio-RVC-Fork/issues/102) it isn't even reporting smth it just says "im going to switch to mangio if you don't fix this immediately" remember that every pc is different and everyone doesn't have the same configs has you. thanks
> 
> my bad yo

don't worry also im doing the thing for select downloaders in the bat. that should solve this issue

**Comment by HyperChocolat** [comment]
Ok so this https://github.com/IAHispano/Applio-RVC-Fork/pull/105 should fix this issue but need testing

**Comment by HyperChocolat** [comment]
this commit should fix it too https://github.com/IAHispano/Applio-RVC-Fork/commit/a582b20549c01520e36f215b7a88a530ddf7618e

**Comment by HyperChocolat** [comment]
this issue can be closed since is solved
